<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>3.1.0</Version>
		<Author>vnbaaij</Author>
		<Company>Baaijte</Company>
		<Description>Use SixLabors.ImageSharp.Web in Optimizely</Description>
		<Copyright>Copyright 2026, Vincent Baaij</Copyright>
		<PackageProjectUrl>https://github.com/vnbaaij/Baaijte.Optimizely.ImageSharp.Web</PackageProjectUrl>
		<RepositoryUrl>https://github.com/vnbaaij/Baaijte.Optimizely.ImageSharp.Web</RepositoryUrl>
		<PackageTags>Optimizely ImageSharp Blob Cache</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<ProduceReferenceAssembly>False</ProduceReferenceAssembly>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="modules\**" />
		<EmbeddedResource Remove="modules\**" />
		<None Remove="modules\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EPiServer.CMS" Version="[12.34.2,13.0.0)" />
		<PackageReference Include="EPiServer.ImageLibrary.ImageSharp" Version="2.0.5" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="SixLabors.ImageSharp.Web" Version="[3.2.0,4.0.0)" />
		<PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.2.0" />
	</ItemGroup>

</Project>
